name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to server
      env:
        GH_TOKEN: "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"
      run: |
        ssh gce@34.93.137.125 "cd /mnt/disks/disk1/web/web/DrupalDev && sudo git pull origin master"
